### ISSUE TITLE
How to build this project

### ISSUE THREAD

**Issue by ledunguit** [HideakiAtsuyo/ReallyBasicExampleProtector-Obfuscator#2]
I don't see any .sln file that can be open with VS, how can we build this project. Thanks

**Comment by HideakiAtsuyo** [comment]
> I don't see any .sln file that can be open with VS, how can we build this project. Thanks

Still not solved ? Sorry i don't have the issues notifications !

**Comment by ledunguit** [comment]
Sorry about that, after five minutes, don't need the .sln fiile :)) Thank you for reply.

**Comment by HideakiAtsuyo** [comment]
> Sorry about that, after five minutes, I realized that the project can be opened with the .csproj file ;)) don't need the .sln fiile :)) Thank you for reply.

No problem ! :)
